language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
addons:
  apt:
    packages:
    - pandoc
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - pip install codacy-coverage
script:
  - nosetests
  - make install
after_script:
  - yes | pip uninstall qmon
  - pip install qmon
after_success:
  - make coverage
  - python-codacy-coverage -r coverage.xml
  - coveralls
